# Generated by Django 4.1.7 on 2023-05-14 16:28

from django.db import migrations
from faker import Faker

fake = Faker()


def start(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Category = apps.get_model('products', 'Category')
    # products = []
    for _ in range(100):
        product = Product.objects.create(
            name=fake.word(),
            description=fake.sentence(),
            sku=fake.random_number(),
            price=fake.pydecimal(left_digits=4, right_digits=2, positive=True)
        )
        product.categories.add(
            Category.objects.create(
                name=fake.word(),
                description=fake.sentence(),
            )
        )
    # Product.objects.bulk_create(products)


def end(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Product.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_category_discount_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RunPython(
            start,
            end
        )
    ]
